plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.transferwatch'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.transferwatch"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.11.0'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
}